name: CI - Build and Push to ECR

on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_NAME: strapi-app
  IMAGE_TAG: latest
  ECR_IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/strapi-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR repository if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY_NAME || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY_NAME

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY_NAME:$IMAGE_TAG .

      - name: Tag Docker image with full ECR URI
        run: |
          docker tag $ECR_REPOSITORY_NAME:$IMAGE_TAG $ECR_IMAGE_URI:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_IMAGE_URI:$IMAGE_TAG

      - name: Set image tag as output
        id: image_tag
        run: echo "image_tag=$ECR_IMAGE_URI:$IMAGE_TAG" >> $GITHUB_OUTPUT
