name: CD - Deploy to ECS with CodeDeploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPO: strapi-app
  SERVICE_NAME: strapi-service
  CLUSTER_NAME: strapi-cluster
  CODEDEPLOY_APP: strapi-codedeploy-app
  DEPLOYMENT_GROUP: strapi-deployment-group

jobs:
  deploy:
    name: Deploy to ECS Fargate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get latest task definition
        id: taskdef
        run: |
          TASK_DEF_ARN=$(aws ecs describe-task-definition \
            --task-definition strapi-task \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Replace task ARN in appspec.json
        run: |
          sed -i "s|REPLACEME_TASK_DEFINITION_ARN|${{ env.TASK_DEF_ARN }}|g" appspec.json

      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APP \
            --deployment-group-name $DEPLOYMENT_GROUP \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --region $AWS_REGION \
            --description "Strapi Blue/Green Deployment" \
            --revision file://appspec.json
