name: CD - Deploy to ECS with CodeDeploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create deployment using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name strapi-application \
            --deployment-group-name strapi-deployment-group \
            --revision file://appspec.json \
            --region us-east-1

      - name: Generate deploy-revision.json
        run: |
          echo '{
            "revisionType": "GitHub",
            "gitHubLocation": {
              "repository": "DDhanavandhan/strapi_ecs_deploy",
              "commitId": "${{ github.sha }}"
            }
          }' > deploy-revision.json
