name: CD - Deploy Strapi to ECS

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  
env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy to ECS using Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Change if needed

    - name: Terraform fmt
      run: terraform fmt -check
      working-directory: ./terraform  # Change if needed

    - name: Terraform plan
      run: terraform plan -input=false
      working-directory: ./terraform  # Change if needed

    - name: Terraform destroy
      run: |
        terraform destroy -auto-approve -var="ecr_image=${{ github.event.inputs.ecr_image }}"
      working-directory: ./terraform  # Change if needed