name: CD - Destroy Strapi Resources

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy ECS and related resources'
        required: true
        default: 'false'

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    name: Destroy ECS Resources using Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Change if needed

    - name: Terraform Destroy
      if: ${{ github.event.inputs.destroy == 'true' }}  # Only run destroy if the input is 'true'
      run: |
        terraform destroy -auto-approve
      working-directory: ./terraform  # Change if needed
