name: CD - Deploy Strapi to ECS

on:
  workflow_dispatch:
    inputs:
      ecr_image:
        description: 'Full ECR image URL (e.g., 123456789012.dkr.ecr.us-east-1.amazonaws.com/strapi-app:latest)'
        required: true

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy to ECS using Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Change if needed

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -var="ecr_image=${{ github.event.inputs.ecr_image }}"
      working-directory: ./terraform  # Change if needed
